version: "3.9"

services:

  nginx:
    build:
      context: ./docker/nginx
    container_name: "${CONTAINER_PREFIX}_${CONTAINER_NAME}_nginx"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./docker/nginx/conf/nginx_${CONTAINER_PREFIX}.conf:/etc/nginx/conf.d/x_nginx.conf"
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./src:/var/www
      - ./docker/runtime/logs:/var/log/nginx
    depends_on:
      - php
    entrypoint: ["nginx-debug", "-g", "daemon off;"]
    networks:
      xweb:
        aliases:
          - x.not-real.ru

  php:
    build:
      context: ./docker/php
      args:
        - WITH_XDEBUG=true
        - APP_ENV=${APP_ENV}
    env_file: .env
    container_name: "${CONTAINER_PREFIX}_${CONTAINER_NAME}_php"
    restart: always
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
      PHP_ENABLE_XDEBUG: 1
    depends_on:
      - postgres
    volumes:
      - ./src:/var/www
      - "${PHP_INI_DIR}/php.ini:/usr/local/etc/php/conf.d/xx-custom.ini"
    ports:
      - "8080:8080"
    networks:
      xweb:
        aliases:
          - x.not-real.ru

  postgres:
    env_file:
      - .env
    hostname: "${CONTAINER_PREFIX}_${CONTAINER_NAME}_postgres"
    container_name: "${CONTAINER_PREFIX}_${CONTAINER_NAME}_postgres"
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgre/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: "/var/lib/postgre/data/pgdata"
    networks:
      xweb:
        aliases:
          - x.not-real.ru

  pgadmin:
    hostname: "${CONTAINER_PREFIX}_${CONTAINER_NAME}_postgres"
    container_name: "${CONTAINER_PREFIX}_${CONTAINER_NAME}_pgadmin"
    restart: always
    build:
      context: docker/pgadmin
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=True
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin/data
    networks:
      xweb:
        aliases:
          - x.not-real.ru
volumes:
  src:
    driver: local
  pgdata:
    driver: local
  pgadmin:
    driver: local

networks:
  xweb:
    driver: bridge

